version: 0.2

phases:
  pre_build:
    commands:
       - echo Instalando...
       - npm install
       - npm install -g @angular/cli
       - echo Finished installing NPM dependencies.
  build:
    commands:
       - echo Building...
       - ng build --prod --aot
       - echo Finalizando.
artifacts:
  files:
    - index.html
